/*	Class:			Constants
 *	Purpose:		Header file to define constants
 *	Version:		Thinknowlogy 2016r1 (Huguenot)
 *************************************************************************/
/*	Copyright (C) 2009-2016, Menno Mafait. Your suggestions, modifications,
 *	corrections and bug reports are welcome at http://mafait.org/contact/
 *************************************************************************/
/*	This program is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 2 of the License, or
 *	(at your option) any later version.
 *
 *	This program is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License along
 *	with this program; if not, write to the Free Software Foundation, Inc.,
 *	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *************************************************************************/

#ifndef CONSTANTS
#define CONSTANTS 1

// Constants header

	typedef signed char ResultType;

	// Version constants
	#define PRODUCT_NAME												"Thinknowlogy"
	#define VERSION_NAME												"2016r1 (Huguenot)"

	// Character constants
	#define	SPACE_CHAR													' '
	#define	BACK_SPACE_CHAR												'\b'
	#define	BELL_CHAR													'\a'
	#define	NEW_LINE_CHAR												'\n'
	#define	CARRIAGE_RETURN_CHAR										'\r'
	#define	TAB_CHAR													'\t'
	#define	MAX_ERROR_STRING_LENGTH										500
	#define	MAX_SENTENCE_STRING_LENGTH									2000

	// File constants
	#define	FILE_DATA_EXAMPLES_DIRECTORY_NAME_STRING					"data/examples/"
	#define	FILE_DATA_GRAMMAR_DIRECTORY_NAME_STRING						"data/grammar/"
	#define	FILE_DATA_INFO_DIRECTORY_NAME_STRING						"data/info/"
	#define	FILE_DATA_INTERFACE_DIRECTORY_NAME_STRING					"data/interface/"
	#define	FILE_DATA_STARTUP_DIRECTORY_NAME_STRING						"data/startup/"
	#define	FILE_DATA_REGRESSION_TEST_OUTPUT_DIRECTORY_NAME_STRING		"data/regression/output/"
	#define	FILE_DATA_REGRESSION_TEST_REFERENCE_DIRECTORY_NAME_STRING	"data/regression/reference/"

	#define	FILE_STARTUP_NAME_STRING									"startup"
	#define	FILE_WINDOWS_VERSION_STRING									"Español"
	#define	FILE_EXTENSION_STRING										".txt"
	#define	FILE_ATTRIBUTES_READ_TEXT_UTF_8								"rt+, ccs=UTF-8"
	#define	FILE_ATTRIBUTES_WRITE_TEXT_UTF_8							"wt+, ccs=UTF-8"
	#define	FILE_UTF_8_BOM_LENGTH										3
	#define	FILE_UTF_8_BOM_CHAR_1										0xFFEF
	#define	FILE_UTF_8_BOM_CHAR_2										0xFFBB
	#define	FILE_UTF_8_BOM_CHAR_3										0xFFBF

	// Grammar constants
	#define	GRAMMAR_CHOICE_START										SYMBOL_OPEN_CURVED_BRACKET
	#define	GRAMMAR_CHOICE_END											SYMBOL_CLOSE_CURVED_BRACKET
	#define	GRAMMAR_OPTION_START										SYMBOL_OPEN_SQUARE_BRACKET
	#define	GRAMMAR_OPTION_END											SYMBOL_CLOSE_SQUARE_BRACKET
	#define	GRAMMAR_OPTION_READ_NOT_WRITE_START							SYMBOL_OPEN_ROUNDED_BRACKET
	#define	GRAMMAR_OPTION_READ_NOT_WRITE_END							SYMBOL_CLOSE_ROUNDED_BRACKET

	// Initialization constants
	#define	NO_ASSIGNMENT_LEVEL											0
	#define	NO_ASSUMPTION_LEVEL											0
	#define	NO_GRAMMAR_LEVEL											0
	#define	NO_SELECTION_LEVEL											0
	#define	NO_SOLVE_LEVEL												0
	#define	NO_WRITE_LEVEL												0
	#define	NO_LANGUAGE_NR												0
	#define	NO_ORDER_NR													0
	#define	NO_USER_NR													0

	#define	NO_ADJECTIVE_PARAMETER										0
	#define	NO_ANSWER_PARAMETER											0
	#define	NO_ASSIGNMENT_PARAMETER										0
	#define	NO_DEFINITE_ARTICLE_PARAMETER								0
	#define	NO_GRAMMAR_PARAMETER										0
	#define	NO_IMPERATIVE_PARAMETER										0
	#define	NO_INDEFINITE_ARTICLE_PARAMETER								0
	#define	NO_INTERFACE_PARAMETER										0
	#define	NO_PREPOSITION_PARAMETER									0
	#define	NO_QUESTION_PARAMETER										0
	#define	NO_SOLVE_STRATEGY_PARAMETER									0
	#define	NO_WORD_PARAMETER											0

	#define	NO_LIST_NR													USHRT_MAX
	#define	MAX_LEVEL													USHRT_MAX
	#define	MAX_ORDER_NR												USHRT_MAX
	#define	MAX_POSITION												USHRT_MAX

	#define	NO_CENTER_WIDTH												0
	#define	NO_COLLECTION_NR											0
	#define	NO_CONTEXT_NR												0
	#define	NO_ITEM_NR													0
	#define	NO_SCORE													0
	#define	NO_SENTENCE_NR												0

	#define	MAX_COLLECTION_NR											UINT_MAX
	#define	MAX_CONTEXT_NR												UINT_MAX
	#define	MAX_ITEM_NR													UINT_MAX
	#define	MAX_NUMBER													UINT_MAX
	#define	MAX_PROGRESS												UINT_MAX
	#define	MAX_QUERY_PARAMETER											UINT_MAX
	#define	MAX_SCORE													UINT_MAX
	#define	MAX_SENTENCE_NR												UINT_MAX
	#define	WINNING_SCORE												UINT_MAX


	// Presentation error constants
	#define	PRESENTATION_ERROR_CONSTRUCTOR_FUNCTION_NAME				"<init>"
	#define	PRESENTATION_ERROR_CURRENT_ID_START_STRING					"\nCurrent item id: "
	#define	PRESENTATION_ERROR_CURRENT_ID_END_STRING					".\n"
	#define	PRESENTATION_ERROR_CLASS_STRING								"\nClass: "
	#define	PRESENTATION_ERROR_SUPERCLASS_STRING						" / superclass "
	#define	PRESENTATION_ERROR_FUNCTION_STRING							".\nFunction: "
	#define	PRESENTATION_ERROR_FUNCTION_WORD_START_STRING				" of word \""
	#define	PRESENTATION_ERROR_FUNCTION_WORD_END_STRING					"\""
	#define	PRESENTATION_ERROR_FUNCTION_LIST_START_STRING				" in list <"
	#define	PRESENTATION_ERROR_FUNCTION_LIST_END_STRING					">"
	#define	PRESENTATION_ERROR_STRING									".\nError: "


	// Presentation prompt constants
	#define PRESENTATION_PROMPT_READ									0
	#define PRESENTATION_PROMPT_WRITE									1
	#define PRESENTATION_PROMPT_WRITE_INDENTED							2
	#define	PRESENTATION_PROMPT_INFO									4
	#define	PRESENTATION_PROMPT_NOTIFICATION							5
	#define PRESENTATION_PROMPT_WARNING									6
	#define PRESENTATION_PROMPT_WARNING_INDENTED						7
	#define PRESENTATION_PROMPT_QUERY									8
//	#define PRESENTATION_PROMPT_ENTER									9

	#define	PRESENTATION_PROMPT_READ_STRING								"> "
	#define	PRESENTATION_PROMPT_WRITE_STRING							"< "
	#define	PRESENTATION_PROMPT_WRITE_INDENTED_STRING					"<	- "
	#define	PRESENTATION_PROMPT_INFO_STRING								""
	#define	PRESENTATION_PROMPT_NOTIFICATION_STRING						"* "
	#define	PRESENTATION_PROMPT_WARNING_STRING							"! "
	#define	PRESENTATION_PROMPT_WARNING_INDENTED_STRING					"!	- "
	#define	PRESENTATION_PROMPT_QUERY_STRING							"? "
	#define	PRESENTATION_PROMPT_ENTER_STRING							": "
	#define	PRESENTATION_PROMPT_EMPTY_STRING							"  "

	#define	PRESENTATION_SKIP_COMMENT_STRING							"#Java#"
	#define	PRESENTATION_STRIP_COMMENT_STRING							"#C++#"

	// Query constants
	#define	COMMENT_CHAR												SYMBOL_HASH
	#define	GRAMMAR_WORD_DEFINITION_CHAR								SYMBOL_DOLLAR

	#define	QUERY_CHAR													SYMBOL_SWUNG_DASH
	#define	QUERY_COUNT_CHAR											SYMBOL_HASH
	#define	QUERY_SELECTING_ATTACHED_JUSTIFICATIONS_CHAR				SYMBOL_ASTERISK
	#define	QUERY_NO_LIST_CHAR											SYMBOL_QUESTION_MARK
	#define	QUERY_WORD_TYPE_CHAR										SYMBOL_AT_SIGN
	#define	QUERY_PARAMETER_CHAR										SYMBOL_DOUBLE_COLON
	#define	QUERY_ACTIVE_CHAR											SYMBOL_PLUS
	#define	QUERY_INACTIVE_CHAR											SYMBOL_EQUALITY
	#define	QUERY_ARCHIVED_CHAR											SYMBOL_DOLLAR
	#define	QUERY_REPLACED_CHAR											SYMBOL_PERCENT
	#define	QUERY_DELETED_CHAR											SYMBOL_AMPERSAND
	#define	QUERY_SEPARATOR_CHAR										SYMBOL_COMMA
	#define	QUERY_ITEM_START_CHAR										SYMBOL_OPEN_ROUNDED_BRACKET
	#define	QUERY_ITEM_END_CHAR											SYMBOL_CLOSE_ROUNDED_BRACKET
	#define	QUERY_ITEM_SENTENCE_NR_START_CHAR							SYMBOL_OPEN_CURVED_BRACKET
	#define	QUERY_ITEM_SENTENCE_NR_END_CHAR								SYMBOL_CLOSE_CURVED_BRACKET
	#define	QUERY_REF_ITEM_START_CHAR									SYMBOL_OPEN_SQUARE_BRACKET
	#define	QUERY_REF_ITEM_END_CHAR										SYMBOL_CLOSE_SQUARE_BRACKET
	#define	QUERY_LIST_START_CHAR										SYMBOL_OPEN_HOOKED_BRACKET
	#define	QUERY_LIST_END_CHAR											SYMBOL_CLOSE_HOOKED_BRACKET
	#define	QUERY_WORD_START_CHAR										SYMBOL_QUOTE
	#define	QUERY_WORD_END_CHAR											SYMBOL_QUOTE
	#define	QUERY_WORD_REFERENCE_START_CHAR								SYMBOL_BACK_QUOTE
	#define	QUERY_WORD_REFERENCE_END_CHAR								SYMBOL_BACK_QUOTE
	#define	QUERY_STRING_START_CHAR										SYMBOL_DOUBLE_QUOTE
	#define	QUERY_STRING_END_CHAR										SYMBOL_DOUBLE_QUOTE

	#define	QUERY_SEPARATOR_SPACE_STRING								", "
	#define	QUERY_SEPARATOR_STRING										","

	#define	TEXT_BELL_CHAR												'a'
	#define	TEXT_BACK_SPACE_CHAR										'b'
	#define TEXT_NEW_LINE_CHAR											'n'
	#define	TEXT_TAB_CHAR												't'

	// Result constants
	#define	RESULT_OK													1
	#define	RESULT_ERROR												0
	#define	RESULT_SYSTEM_ERROR											-1

	// Screen constants
	#define	TAB_LENGTH													8
	#define	NUMBER_OF_CONSOLE_COLUMNS									80

	// String constants
	#define	ASTERISK_STRING												"*"
	#define	COLON_STRING												"."
	#define	EMPTY_STRING												""
	#define	SLASH_STRING												"/"
	#define	SPACE_STRING												" "
	#define	BELL_STRING													"\a"
	#define	CARRIAGE_RETURN_STRING										"\r"
	#define	NEW_LINE_STRING												"\n"
	#define	EMPTY_WIDE_STRING											L""
	#define	SPACE_WIDE_STRING											L" "

	// Symbol constants
	#define	SYMBOL_COMMA												','
	#define	SYMBOL_COLON												'.'
	#define	SYMBOL_SEMI_COLON											';'
	#define	SYMBOL_DOUBLE_COLON											':'
	#define	SYMBOL_EXCLAMATION_MARK										'!'
#ifdef _MSC_VER
	#define	SYMBOL_EXCLAMATION_MARK_INVERTED							'¡'
#endif
	#define	SYMBOL_QUESTION_MARK										'?'
#ifdef _MSC_VER
	#define	SYMBOL_QUESTION_MARK_INVERTED								'¿'
#endif
	#define	SYMBOL_PLUS													'+'
	#define	SYMBOL_EQUALITY												'='
	#define	SYMBOL_PIPE													'|'
	#define	SYMBOL_AMPERSAND											'&'
	#define	SYMBOL_HASH													'#'
	#define	SYMBOL_SWUNG_DASH											'~'
	#define	SYMBOL_AT_SIGN												'@'
	#define	SYMBOL_ASTERISK												'*'
	#define	SYMBOL_PERCENT												'%'
	#define	SYMBOL_DOLLAR												'$'
	#define	SYMBOL_SLASH												'/'
	#define	SYMBOL_BACK_SLASH											'\\'
	#define	SYMBOL_QUOTE												'\''
	#define	SYMBOL_BACK_QUOTE											'`'
	#define	SYMBOL_DOUBLE_QUOTE											'"'
	#define	SYMBOL_OPEN_ROUNDED_BRACKET									'('
	#define	SYMBOL_CLOSE_ROUNDED_BRACKET								')'
	#define	SYMBOL_OPEN_CURVED_BRACKET									'{'
	#define	SYMBOL_CLOSE_CURVED_BRACKET									'}'
	#define	SYMBOL_OPEN_HOOKED_BRACKET									'<'
	#define	SYMBOL_CLOSE_HOOKED_BRACKET									'>'
	#define	SYMBOL_OPEN_SQUARE_BRACKET									'['
	#define	SYMBOL_CLOSE_SQUARE_BRACKET									']'


	// Administrator initialization constants

	#define	ADMIN_FILE_LIST												0
	#define	ADMIN_READ_LIST												2
	#define	ADMIN_SCORE_LIST											3
	#define	ADMIN_WORD_LIST												4
	#define	ADMIN_CONDITION_LIST										5		// SelectionItem
	#define	ADMIN_ACTION_LIST											6		// SelectionItem
	#define	ADMIN_ALTERNATIVE_LIST										7		// SelectionItem
	#define	NUMBER_OF_ADMIN_LISTS										8

	#define	ADMIN_FILE_LIST_SYMBOL										'F'
	#define	ADMIN_READ_LIST_SYMBOL										'R'
	#define	ADMIN_SCORE_LIST_SYMBOL										'S'
	#define	ADMIN_WORD_LIST_SYMBOL										'W'
	#define	ADMIN_CONDITION_LIST_SYMBOL									'X'		// SelectionItem
	#define	ADMIN_ACTION_LIST_SYMBOL									'Y'		// SelectionItem
	#define	ADMIN_ALTERNATIVE_LIST_SYMBOL								'Z'		// SelectionItem

	// Word initialization constants

	#define	WORD_ASSIGNMENT_LIST										0		// SpecificationItem
	#define	WORD_COLLECTION_LIST										1
	#define	WORD_GENERALIZATION_LIST									2
	#define	WORD_INTERFACE_LIST											3
	#define	WORD_JUSTIFICATION_LIST										4
	#define	WORD_GRAMMAR_LIST											5
	#define	WORD_MULTIPLE_WORD_LIST										6
	#define	WORD_WRITE_LIST												7
	#define	WORD_SPECIFICATION_LIST										8
	#define	WORD_TYPE_LIST												9
	#define	WORD_CONTEXT_LIST											10
	#define	NUMBER_OF_WORD_LISTS										11

	#define	WORD_ASSIGNMENT_LIST_SYMBOL									'a'		// SpecificationItem
	#define	WORD_COLLECTION_LIST_SYMBOL									'c'
	#define	WORD_GENERALIZATION_LIST_SYMBOL								'g'
	#define	WORD_INTERFACE_LIST_SYMBOL									'i'
	#define	WORD_JUSTIFICATION_LIST_SYMBOL								'j'
	#define	WORD_GRAMMAR_LIST_SYMBOL									'l'
	#define	WORD_MULTIPLE_WORD_LIST_SYMBOL								'm'
	#define	WORD_WRITE_LIST_SYMBOL										'r'
	#define	WORD_SPECIFICATION_LIST_SYMBOL								's'
	#define	WORD_TYPE_LIST_SYMBOL										'w'
	#define	WORD_CONTEXT_LIST_SYMBOL									'x'

	// Other initialization constants
	#define FUNCTION_NAME_LENGTH										80
	#define MAX_ASSUMPTION_LEVEL_RECALCULATIONS							1000	// Number of repeated calculations
	#define MAX_GRAMMAR_LEVEL											50		// Depth of grammar parsing
	#define MAX_SELECTION_EXECUTIONS									1000	// Number of repeated selections
	#define	MAX_WORD_LENGTH												100

	#define NUMBER_OF_ASSUMPTION_LEVELS									3		// Probably, possibly and maybe
	#define	NUMBER_OF_PHONETIC_VOWELS									4

	const char PHONETIC_VOWEL[NUMBER_OF_PHONETIC_VOWELS] =			{	'a',
																		'e',
																		'i',
																		'o' };


	// Justification types
	#define	JUSTIFICATION_TYPE_GENERALIZATION_ASSUMPTION									0
	#define	JUSTIFICATION_TYPE_OPPOSITE_POSSESSIVE_CONDITIONAL_SPECIFICATION_ASSUMPTION		1
	#define	JUSTIFICATION_TYPE_EXCLUSIVE_SPECIFICATION_SUBSTITUTION_ASSUMPTION				2
	#define	JUSTIFICATION_TYPE_INDIRECTLY_ANSWERED_QUESTION_ASSUMPTION						3
	#define	JUSTIFICATION_TYPE_SUGGESTIVE_QUESTION_ASSUMPTION								4

	#define	JUSTIFICATION_TYPE_ONLY_OPTION_LEFT_ASSUMPTION									5
	#define	JUSTIFICATION_TYPE_POSSESSIVE_REVERSIBLE_ASSUMPTION								6
	#define	JUSTIFICATION_TYPE_DEFINITION_PART_OF_ASSUMPTION								7
	#define	JUSTIFICATION_TYPE_NEGATIVE_ASSUMPTION											8
	#define	JUSTIFICATION_TYPE_SPECIFICATION_GENERALIZATION_SUBSTITUTION_ASSUMPTION			9
	#define	JUSTIFICATION_TYPE_SPECIFICATION_SUBSTITUTION_ASSUMPTION						10
	#define	JUSTIFICATION_TYPE_SPECIFICATION_SUBSTITUTION_PART_OF_ASSUMPTION				11
	#define	JUSTIFICATION_TYPE_UNIQUE_RELATION_ASSUMPTION									12

	#define	JUSTIFICATION_TYPE_ONLY_OPTION_LEFT_CONCLUSION									13
	#define	JUSTIFICATION_TYPE_POSSESSIVE_REVERSIBLE_CONCLUSION								14
	#define	JUSTIFICATION_TYPE_DEFINITION_PART_OF_CONCLUSION								15
	#define	JUSTIFICATION_TYPE_NEGATIVE_CONCLUSION											16
	#define	JUSTIFICATION_TYPE_SPECIFICATION_GENERALIZATION_SUBSTITUTION_CONCLUSION			17
	#define	JUSTIFICATION_TYPE_SPECIFICATION_SUBSTITUTION_CONCLUSION						18
	#define	JUSTIFICATION_TYPE_SPECIFICATION_SUBSTITUTION_PART_OF_CONCLUSION				19
	#define	JUSTIFICATION_TYPE_UNIQUE_RELATION_CONCLUSION									20

	#define	JUSTIFICATION_TYPE_SPECIFICATION_SUBSTITUTION_QUESTION							21


	// Word types
	#define	WORD_TYPE_UNDEFINED										0
	#define	WORD_TYPE_SYMBOL										1
	#define	WORD_TYPE_NUMERAL										2
	#define	WORD_TYPE_LETTER_SMALL									3
	#define	WORD_TYPE_LETTER_CAPITAL								4
	#define	WORD_TYPE_PROPER_NAME									5
	#define	WORD_TYPE_ADJECTIVE										6
	#define	WORD_TYPE_ADVERB										7
	#define	WORD_TYPE_ANSWER										8
	#define	WORD_TYPE_ARTICLE										9
	#define	WORD_TYPE_CONJUNCTION									10
	#define	WORD_TYPE_NOUN_SINGULAR									11
	#define	WORD_TYPE_NOUN_PLURAL									12
	#define	WORD_TYPE_PERSONAL_PRONOUN_SINGULAR_SUBJECTIVE			13
	#define	WORD_TYPE_PERSONAL_PRONOUN_SINGULAR_OBJECTIVE			14
	#define	WORD_TYPE_POSSESSIVE_DETERMINER_SINGULAR				15
	#define	WORD_TYPE_POSSESSIVE_PRONOUN_SINGULAR					16
	#define	WORD_TYPE_PERSONAL_PRONOUN_PLURAL_SUBJECTIVE			17
	#define	WORD_TYPE_PERSONAL_PRONOUN_PLURAL_OBJECTIVE				18
	#define	WORD_TYPE_POSSESSIVE_DETERMINER_PLURAL					19
	#define	WORD_TYPE_POSSESSIVE_PRONOUN_PLURAL						20
	#define	WORD_TYPE_PREPOSITION									21
	#define	WORD_TYPE_VERB_SINGULAR									22
	#define	WORD_TYPE_VERB_PLURAL									23
	#define	WORD_TYPE_SELECTION_WORD								24
	#define	WORD_TYPE_TEXT											25
	#define	NUMBER_OF_WORD_TYPES									26


	// Word Parameters

	// Symbols
	#define	WORD_PARAMETER_SYMBOL_COMMA												100
	#define	WORD_PARAMETER_SYMBOL_COLON												101
	#define	WORD_PARAMETER_SYMBOL_EXCLAMATION_MARK									102
	#define	WORD_PARAMETER_SYMBOL_EXCLAMATION_MARK_INVERTED							103
	#define	WORD_PARAMETER_SYMBOL_QUESTION_MARK										104
	#define	WORD_PARAMETER_SYMBOL_QUESTION_MARK_INVERTED							105

	// Numerals
	#define	WORD_PARAMETER_NUMERAL_BOTH												200

	// Small letters

	// Capital letters

	// Proper-names

	// Adjectives
	#define	WORD_PARAMETER_ADJECTIVE_ASSIGNED										600
	#define	WORD_PARAMETER_ADJECTIVE_BUSY											601
	#define	WORD_PARAMETER_ADJECTIVE_DONE											602
	#define	WORD_PARAMETER_ADJECTIVE_DEFENSIVE										603
	#define	WORD_PARAMETER_ADJECTIVE_EMPTY											604
	#define	WORD_PARAMETER_ADJECTIVE_EXCLUSIVE										605
	#define	WORD_PARAMETER_ADJECTIVE_INVERTED										606
	#define	WORD_PARAMETER_ADJECTIVE_FEMININE										607
	#define	WORD_PARAMETER_ADJECTIVE_MASCULINE										608
	#define	WORD_PARAMETER_ADJECTIVE_NO												609
	#define	WORD_PARAMETER_ADJECTIVE_CALLED_PLURAL									610
	#define	WORD_PARAMETER_ADJECTIVE_CALLED_SINGULAR_FEMININE						611
	#define	WORD_PARAMETER_ADJECTIVE_CALLED_SINGULAR_MASCULINE						612
	#define	WORD_PARAMETER_ADJECTIVE_EVERY_NEUTRAL									613
	#define	WORD_PARAMETER_ADJECTIVE_EVERY_FEMININE_MASCULINE						614
	#define	WORD_PARAMETER_ADJECTIVE_PREVIOUS_NEUTRAL								615
	#define	WORD_PARAMETER_ADJECTIVE_PREVIOUS_FEMININE_MASCULINE					616
	#define	WORD_PARAMETER_ADJECTIVE_CURRENT_NEUTRAL								617
	#define	WORD_PARAMETER_ADJECTIVE_CURRENT_FEMININE_MASCULINE						618
	#define	WORD_PARAMETER_ADJECTIVE_NEW_NEUTRAL									619
	#define	WORD_PARAMETER_ADJECTIVE_NEW_FEMININE_MASCULINE							620
//	#define	WORD_PARAMETER_ADJECTIVE_NEXT_NEUTRAL									621
//	#define	WORD_PARAMETER_ADJECTIVE_NEXT_FEMININE_MASCULINE						622
	#define	WORD_PARAMETER_ADJECTIVE_ODD											623
	#define	WORD_PARAMETER_ADJECTIVE_EVEN											624
	#define	WORD_PARAMETER_ADJECTIVE_EARLIER										625
	#define	WORD_PARAMETER_ADJECTIVE_LESS											626
	#define	WORD_PARAMETER_ADJECTIVE_LOWER											627
	#define	WORD_PARAMETER_ADJECTIVE_SMALLER										628
	#define	WORD_PARAMETER_ADJECTIVE_EQUAL											629
	#define	WORD_PARAMETER_ADJECTIVE_SAME											630
	#define	WORD_PARAMETER_ADJECTIVE_BIGGER											631
	#define	WORD_PARAMETER_ADJECTIVE_HIGHER											632
	#define	WORD_PARAMETER_ADJECTIVE_LARGER											633
	#define	WORD_PARAMETER_ADJECTIVE_LATER											634
	#define	WORD_PARAMETER_ADJECTIVE_MORE											635

	// Adverbs
	#define	WORD_PARAMETER_ADVERB_ANYMORE											700
	#define	WORD_PARAMETER_ADVERB_AS												701
	#define	WORD_PARAMETER_ADVERB_ASSUMPTION_MAYBE									702
	#define	WORD_PARAMETER_ADVERB_ASSUMPTION_POSSIBLY								703
	#define	WORD_PARAMETER_ADVERB_ASSUMPTION_PROBABLY								704
	#define	WORD_PARAMETER_ADVERB_NOT												705
	#define	WORD_PARAMETER_ADVERB_NOT_FRENCH										706

	// Interjections
	#define	WORD_PARAMETER_INTERJECTION_YES											800
	#define	WORD_PARAMETER_INTERJECTION_NO											801

	// Articles
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_PHONETIC_VOWEL_PLURAL_FEMININE		900
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_PHONETIC_VOWEL_PLURAL_MASCULINE		901
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_PHONETIC_VOWEL_SINGULAR_FEMININE		902
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_PHONETIC_VOWEL_SINGULAR_MASCULINE		903
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_PLURAL_FEMININE						904
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_PLURAL_MASCULINE						905
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_SINGULAR_FEMININE						906
	#define	WORD_PARAMETER_ARTICLE_INDEFINITE_SINGULAR_MASCULINE					907
	#define	WORD_PARAMETER_ARTICLE_DEFINITE_PLURAL_NEUTRAL							908
	#define	WORD_PARAMETER_ARTICLE_DEFINITE_PLURAL_FEMININE							909
	#define	WORD_PARAMETER_ARTICLE_DEFINITE_PLURAL_MASCULINE						910
	#define	WORD_PARAMETER_ARTICLE_DEFINITE_SINGULAR_NEUTRAL						911
	#define	WORD_PARAMETER_ARTICLE_DEFINITE_SINGULAR_FEMININE						912
	#define	WORD_PARAMETER_ARTICLE_DEFINITE_SINGULAR_MASCULINE						913

	// Conjunctions
	#define	WORD_PARAMETER_CONJUNCTION_AND											1000
	#define	WORD_PARAMETER_CONJUNCTION_OR											1001
//	#define	WORD_PARAMETER_CONJUNCTION_THAN											1002
//	#define	WORD_PARAMETER_CONJUNCTION_FRENCH_THAN									1003
	#define	WORD_PARAMETER_CONJUNCTION_DUTCH_ZOWEL									1004
	#define	WORD_PARAMETER_CONJUNCTION_DUTCH_ALS									1005

	// Singular / plural nouns
	#define	WORD_PARAMETER_NOUN_DEVELOPER											1100
	#define	WORD_PARAMETER_NOUN_EXPERT												1101
	#define	WORD_PARAMETER_NOUN_FILE												1102
	#define	WORD_PARAMETER_NOUN_JUSTIFICATION_REPORT								1103
	#define	WORD_PARAMETER_NOUN_HEAD												1104
	#define	WORD_PARAMETER_NOUN_TAIL												1105
	#define	WORD_PARAMETER_NOUN_LANGUAGE											1106
	#define	WORD_PARAMETER_NOUN_MIND												1107
	#define	WORD_PARAMETER_NOUN_NUMBER												1108
	#define	WORD_PARAMETER_NOUN_PASSWORD											1109
	#define	WORD_PARAMETER_NOUN_SOLVE_LEVEL											1110
	#define	WORD_PARAMETER_NOUN_SOLVE_METHOD										1111
	#define	WORD_PARAMETER_NOUN_SOLVE_STRATEGY										1112
	#define	WORD_PARAMETER_NOUN_STARTUP_LANGUAGE									1113
	#define	WORD_PARAMETER_NOUN_TEST_FILE											1114
	#define	WORD_PARAMETER_NOUN_USER												1115
	#define	WORD_PARAMETER_NOUN_INFORMATION											1116
	#define	WORD_PARAMETER_NOUN_PART												1117
	#define	WORD_PARAMETER_NOUN_VALUE												1118

	// Singular pronouns
	#define	WORD_PARAMETER_SINGULAR_PRONOUN_I_ME_MY_MINE							1300
	#define	WORD_PARAMETER_SINGULAR_PRONOUN_YOU_YOUR_YOURS_INFORMAL					1301
	#define	WORD_PARAMETER_SINGULAR_PRONOUN_YOU_YOUR_YOURS_FORMAL					1302
	#define	WORD_PARAMETER_SINGULAR_PRONOUN_HE_HIM_HIS_HIS							1303
	#define	WORD_PARAMETER_SINGULAR_PRONOUN_SHE_HER_HER_HERS						1304
	#define	WORD_PARAMETER_SINGULAR_PRONOUN_IT_ITS_ITS_ITS							1305

	// Plural pronouns
	#define	WORD_PARAMETER_PLURAL_PRONOUN_WE_US_OUR_OURS_FEMININE					1700
	#define	WORD_PARAMETER_PLURAL_PRONOUN_WE_US_OUR_OURS_MASCULINE					1701
	#define	WORD_PARAMETER_PLURAL_PRONOUN_YOU_YOUR_YOURS_FEMININE					1702
	#define	WORD_PARAMETER_PLURAL_PRONOUN_YOU_YOUR_YOURS_MASCULINE					1703
	#define	WORD_PARAMETER_PLURAL_PRONOUN_YOU_ALL									1704
	#define	WORD_PARAMETER_PLURAL_PRONOUN_THEY_THEM_THEIR_THEIRS_FEMININE			1705
	#define	WORD_PARAMETER_PLURAL_PRONOUN_THEY_THEM_THEIR_THEIRS_MASCULINE			1706

	// Prepositions
	#define	WORD_PARAMETER_PREPOSITION_ABOUT										2100
	#define	WORD_PARAMETER_PREPOSITION_FROM											2101
	#define	WORD_PARAMETER_PREPOSITION_IN											2102
	#define	WORD_PARAMETER_PREPOSITION_TO											2103
	#define	WORD_PARAMETER_PREPOSITION_OF											2104
	#define	WORD_PARAMETER_PREPOSITION_FRENCH_A										2105

	// Singular verbs
	#define	WORD_PARAMETER_SINGULAR_VERB_IS											2200
	#define	WORD_PARAMETER_SINGULAR_VERB_WAS										2201
	#define	WORD_PARAMETER_SINGULAR_VERB_CAN_BE										2202
	#define	WORD_PARAMETER_SINGULAR_VERB_HAS										2203
	#define	WORD_PARAMETER_SINGULAR_VERB_HAD										2204
	#define	WORD_PARAMETER_SINGULAR_VERB_CAN_HAVE									2205
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_ADD								2206
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_MOVE							2207
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_REMOVE							2208
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_CLEAR							2209
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_HELP							2210
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_LOGIN							2211
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_READ							2212
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_REDO							2213
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_RESTART							2214
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_SHOW							2215
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_SOLVE							2216
	#define	WORD_PARAMETER_SINGULAR_VERB_IMPERATIVE_UNDO							2217

	// Plural verbs
	#define	WORD_PARAMETER_PLURAL_VERB_ARE											2300
	#define	WORD_PARAMETER_PLURAL_VERB_WERE											2301
	#define	WORD_PARAMETER_PLURAL_VERB_CAN_BE										2302
	#define	WORD_PARAMETER_PLURAL_VERB_HAVE											2303
	#define	WORD_PARAMETER_PLURAL_VERB_HAD											2304
	#define	WORD_PARAMETER_PLURAL_VERB_CAN_HAVE										2305

	// Selection words
	#define	WORD_PARAMETER_SELECTION_IF												2400
	#define	WORD_PARAMETER_SELECTION_THEN											2401
	#define	WORD_PARAMETER_SELECTION_ELSE											2402

	// Text

	// Feminine proper name ending
	#define	WORD_FEMININE_PROPER_NAME_ENDING										3000

	// Masculine proper name ending
	#define	WORD_MASCULINE_PROPER_NAME_ENDING										3001

	// Feminine singular noun ending
	#define	WORD_FEMININE_SINGULAR_NOUN_ENDING										3002

	// Masculine singular noun ending
	#define	WORD_MASCULINE_SINGULAR_NOUN_ENDING										3003

	// Plural noun ending
	#define	WORD_PLURAL_NOUN_ENDING													3004

	// Merged words
	#define	WORD_MERGED_WORD														3005

	// Grammar parameters
	#define GRAMMAR_SENTENCE														4000
	#define	GRAMMAR_SELECTION														5000
	#define	GRAMMAR_IMPERATIVE														5100
	#define	GRAMMAR_ANSWER															5200
	#define	GRAMMAR_GENERALIZATION_SPECIFICATION									6000
	#define	GRAMMAR_GENERALIZATION_PART												6010
	#define	GRAMMAR_GENERALIZATION_WORD												6011
	#define	GRAMMAR_LINKED_GENERALIZATION_CONJUNCTION								6012
	#define	GRAMMAR_SPECIFICATION_PART												6020
	#define	GRAMMAR_ASSIGNMENT_PART													6021
	#define	GRAMMAR_SPECIFICATION_WORD												6022
	#define	GRAMMAR_EXCLUSIVE_SPECIFICATION_CONJUNCTION								6023
	#define	GRAMMAR_RELATION_PART													6030
	#define	GRAMMAR_RELATION_WORD													6031
	#define	GRAMMAR_TEXT															6040
	#define	GRAMMAR_GENERALIZATION_ASSIGNMENT										6100
	#define	GRAMMAR_SPECIFICATION_ASSIGNMENT										6101
	#define	GRAMMAR_RELATION_ASSIGNMENT												6102
	#define	GRAMMAR_SENTENCE_CONJUNCTION											6110
	#define	GRAMMAR_VERB															6120
	#define	GRAMMAR_QUESTION_VERB													6121
	#define	GRAMMAR_SPECIFICATION_GENERALIZATION_VERB								6122
	#define	GRAMMAR_SPECIFICATION_GENERALIZATION_QUESTION_VERB						6123


	// ERROR STRING CONSTANTS

	#define	NO_LANGUAGE_NAME_FOUND_STRING															"{no language name found}"
	#define	NO_USER_NAME_FOUND_STRING																"{no user name found}"
	#define	ADMIN_USER_NAME_STRING																	"Admin"


	// INTERFACE CONSTANTS

	#define	INTERFACE_STRING_NOT_AVAILABLE															"<interface string not available>"
	#define	NO_LANGUAGE_WORD_FOUND																	"<no language word found>"

	// Console (common)
	#define	INTERFACE_CONSOLE_START_MESSAGE															100
	#define	INTERFACE_CONSOLE_ALREADY_LOGGED_IN_START												104
	#define	INTERFACE_CONSOLE_LOGIN_END																105
	#define	INTERFACE_CONSOLE_LOGIN_FAILED															106

	// Console (progress and status)
	#define	INTERFACE_CONSOLE_I_AM_EXECUTING_SELECTIONS_START										110
	#define	INTERFACE_CONSOLE_I_AM_EXECUTING_SELECTIONS_END											111
//	#define	INTERFACE_CONSOLE_I_AM_CLEANING_UP_DELETED_ITEMS										112

	// Grammar
	#define	INTERFACE_GRAMMAR_DEFINITION_IS_NOT_USED_START											1000
	#define	INTERFACE_GRAMMAR_DEFINITION_IS_NOT_USED_MIDDLE											1001
	#define	INTERFACE_GRAMMAR_DEFINITION_IS_NOT_USED_END											1002
	#define	INTERFACE_GRAMMAR_PARAMETER_DEFINED_MORE_THAN_ONCE_START								1003
	#define	INTERFACE_GRAMMAR_PARAMETER_DEFINED_MORE_THAN_ONCE_MIDDLE								1004
	#define	INTERFACE_GRAMMAR_PARAMETER_DEFINED_MORE_THAN_ONCE_END									1005
	#define	INTERFACE_GRAMMAR_WORD_TYPE_DEFINITION_MISSING_START									1006
	#define	INTERFACE_GRAMMAR_WORD_TYPE_DEFINITION_MISSING_MIDDLE									1007
	#define	INTERFACE_GRAMMAR_WORD_TYPE_DEFINITIONS_MISSING_START									1008
	#define	INTERFACE_GRAMMAR_WORD_TYPE_DEFINITIONS_MISSING_TO										1009
	#define	INTERFACE_GRAMMAR_WORD_TYPE_DEFINITIONS_MISSING_MIDDLE									1010
	#define	INTERFACE_GRAMMAR_WORD_TYPE_DEFINITION_MISSING_END										1011
	#define	INTERFACE_GRAMMAR_UNKNOWN_PLURAL_NOUN_START												1012
	#define	INTERFACE_GRAMMAR_UNKNOWN_PLURAL_NOUN_ENDING											1013

	// Query
	#define	INTERFACE_QUERY_NO_ITEM_WAS_FOUND														1100
	#define	INTERFACE_QUERY_NO_REFERENCE_ITEM_WAS_FOUND												1101
	#define	INTERFACE_QUERY_INVALID_CHARACTER_IN_LIST												1102
	#define	INTERFACE_QUERY_NO_LIST_WAS_FOUND														1103
	#define	INTERFACE_QUERY_NO_WORD_WAS_FOUND														1104
	#define	INTERFACE_QUERY_NO_WORD_REFERENCE_WAS_FOUND												1105
	#define	INTERFACE_QUERY_NO_STRING_WAS_FOUND														1106
	#define	INTERFACE_QUERY_NO_WORD_TYPE_WAS_FOUND													1107
	#define	INTERFACE_QUERY_NO_PARAMETER_WAS_FOUND													1108

	#define	INTERFACE_QUERY_NO_ITEMS_WERE_FOUND														1109
	#define	INTERFACE_QUERY_NO_WORDS_WERE_FOUND														1110
	#define	INTERFACE_QUERY_NO_WORD_REFERENCES_WERE_FOUND											1111
	#define	INTERFACE_QUERY_NO_STRINGS_WERE_FOUND													1112

	#define	INTERFACE_QUERY_EMPTY_WORD_SPECIFICATION												1113
	#define	INTERFACE_QUERY_EMPTY_WORD_REFERENCE													1114
	#define	INTERFACE_QUERY_EMPTY_STRING_SPECIFICATION												1115

	#define	INTERFACE_QUERY_ERROR																	1199

	// Imperative (notifications)
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_MY_MIND_IS_CLEAR										1200
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_NO_SENTENCES_TO_UNDO									1201
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_NO_SENTENCES_TO_REDO									1202
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_I_HAVE_UNDONE_SENTENCE_NR_START						1203
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_I_HAVE_UNDONE_SENTENCE_NR_END							1204
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_I_HAVE_REDONE_SENTENCE_NR_START						1205
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_I_HAVE_REDONE_SENTENCE_NR_END							1206
	#define	INTERFACE_IMPERATIVE_NOTIFICATION_I_HAVE_NO												1207

	// Imperative (warnings)
	#define	INTERFACE_IMPERATIVE_WARNING_I_COULD_NOT_FIND_ANY_SELECTION_TO_SOLVE_INFO_START			1210
	#define	INTERFACE_IMPERATIVE_WARNING_I_COULD_NOT_FIND_ANY_SELECTION_TO_SOLVE_INFO_END			1211
	#define	INTERFACE_IMPERATIVE_WARNING_I_DONT_KNOW_HOW_TO_EXECUTE_IMPERATIVE_VERB_START			1212
	#define	INTERFACE_IMPERATIVE_WARNING_I_DONT_KNOW_HOW_TO_EXECUTE_IMPERATIVE_VERB_END				1213
	#define	INTERFACE_IMPERATIVE_WARNING_I_DONT_KNOW_TO_DO_WITH_RELATION							1214
	#define	INTERFACE_IMPERATIVE_WARNING_I_DONT_KNOW_WHICH_FILE_TO_READ								1215
	#define	INTERFACE_IMPERATIVE_WARNING_I_HAVE_NO_INFO_ABOUT_START									1216
	#define	INTERFACE_IMPERATIVE_WARNING_I_HAVE_NO_INFO_ABOUT_END									1217
	#define	INTERFACE_IMPERATIVE_WARNING_NEEDS_A_LIST_TO_BE_SPECIFIED								1218
	#define	INTERFACE_IMPERATIVE_WARNING_PREPOSITION_NOT_USED_FOR_THIS_ACTION						1219
	#define	INTERFACE_IMPERATIVE_WARNING_WORD_ALREADY_SOLVED_START									1220
	#define	INTERFACE_IMPERATIVE_WARNING_WORD_ALREADY_SOLVED_END									1221

	// Justification report
	#define	INTERFACE_JUSTIFICATION_BECAUSE															1300
	#define	INTERFACE_JUSTIFICATION_AND																1301
	#define	INTERFACE_JUSTIFICATION_FEMININE_OR_MASCULINE_PROPER_NAME_ENDING						1302
	#define	INTERFACE_JUSTIFICATION_FEMININE_PROPER_NAME_ENDING										1303
	#define	INTERFACE_JUSTIFICATION_MASCULINE_PROPER_NAME_ENDING									1304
	#define	INTERFACE_JUSTIFICATION_LEARNED_FROM_USER_START											1305
	#define	INTERFACE_JUSTIFICATION_LEARNED_FROM_USER_END											1306

	// Listing (conflicts)
	#define	INTERFACE_LISTING_SENTENCE_IN_CONFLICT_WITH_ITSELF										1400
	#define	INTERFACE_LISTING_QUESTION_IN_CONFLICT_WITH_ITSELF										1401
	#define	INTERFACE_LISTING_CONFLICT																1402
	#define	INTERFACE_LISTING_SENTENCE_DOESNT_LEAVE_ANY_OPTION_OPEN									1403
	#define	INTERFACE_LISTING_SENTENCE_DEFINITION_SPECIFICATION_IS_ALREADY_ASSIGNED					1404
	#define	INTERFACE_LISTING_SENTENCE_ASSIGNMENT_CONFLICTS_WITH_DEFINITION_SPECIFICATION			1405

	// Listing (current information)
	#define	INTERFACE_LISTING_YOUR_INFORMATION														1410
	#define	INTERFACE_LISTING_YOUR_QUESTIONS														1411
	#define	INTERFACE_LISTING_MY_INFORMATION														1412
	#define	INTERFACE_LISTING_MY_CONCLUSIONS														1413
	#define	INTERFACE_LISTING_MY_ASSUMPTIONS														1414
	#define	INTERFACE_LISTING_MY_ASSUMPTIONS_THAT_ARE_ADJUSTED										1415
	#define	INTERFACE_LISTING_MY_ASSUMPTIONS_THAT_ARE_CONCLUDED										1416
	#define	INTERFACE_LISTING_MY_HIDDEN_ASSUMPTIONS_THAT_ARE_CONCLUDED								1417
	#define	INTERFACE_LISTING_MY_ASSUMPTIONS_THAT_ARE_NOT_HIDDEN_ANYMORE							1418
	#define	INTERFACE_LISTING_MY_QUESTIONS															1419
	#define	INTERFACE_LISTING_MY_ADJUSTED_QUESTIONS													1420
	#define	INTERFACE_LISTING_MY_ANSWER																1421
	#define	INTERFACE_LISTING_I_ONLY_KNOW															1422
	#define	INTERFACE_LISTING_I_AM_NOT_SURE_BUT														1423
	#define	INTERFACE_LISTING_SPECIFICATIONS														1424
	#define	INTERFACE_LISTING_SPECIFICATION_QUESTIONS												1425
	#define	INTERFACE_LISTING_RELATED_INFORMATION													1426
	#define	INTERFACE_LISTING_RELATED_QUESTIONS														1427

	// Listing (old information)
	#define	INTERFACE_LISTING_CONFIRMED_SPECIFICATION_OF_MY_ASSUMPTION_BUT_NO_RELATION				1430
	#define	INTERFACE_LISTING_CONFIRMED_SPECIFICATION_OF_MY_CONCLUSION_BUT_NO_RELATION				1431
	#define	INTERFACE_LISTING_CONFIRMED_SPECIFICATION_AND_AT_LEAST_ONE_RELATION_OF_MY_ASSUMPTION	1432
	#define	INTERFACE_LISTING_CONFIRMED_SPECIFICATION_AND_AT_LEAST_ONE_RELATION_OF_MY_CONCLUSION	1433
	#define	INTERFACE_LISTING_MY_ASSUMPTIONS_THAT_ARE_CONFIRMED										1434
	#define	INTERFACE_LISTING_MY_CONCLUSIONS_THAT_ARE_CONFIRMED										1435
	#define	INTERFACE_LISTING_YOUR_INFO_IS_MORE_SPECIFIC_THAN_MY_ASSUMPTION							1436
	#define	INTERFACE_LISTING_YOUR_INFO_IS_MORE_SPECIFIC_THAN_MY_CONCLUSION							1437
	#define	INTERFACE_LISTING_YOUR_QUESTION_IS_MORE_SPECIFIC_THAN_MY_QUESTION						1438
	#define	INTERFACE_LISTING_THIS_INFO_IS_MORE_SPECIFIC_THAN_YOUR_EARLIER_INFO						1439
	#define	INTERFACE_LISTING_THIS_QUESTION_IS_MORE_SPECIFIC_THAN_YOUR_QUESTION						1440
	#define	INTERFACE_LISTING_YOUR_QUESTIONS_THAT_ARE_ANSWERED										1441
	#define	INTERFACE_LISTING_MY_QUESTIONS_THAT_ARE_ANSWERED										1442
	#define	INTERFACE_LISTING_MY_CORRECTED_ASSUMPTIONS_BY_KNOWLEDGE									1443
	#define	INTERFACE_LISTING_MY_CORRECTED_ASSUMPTIONS_BY_OPPOSITE_QUESTION							1444

	// Question
	#define	INTERFACE_QUESTION_YOU_HAD_THE_SAME_QUESTION_BEFORE										1500
	#define	INTERFACE_QUESTION_I_HAD_THE_SAME_QUESTION_BEFORE										1501
	#define	INTERFACE_QUESTION_YOU_HAD_A_SIMILAR_QUESTION_BEFORE									1502
	#define	INTERFACE_QUESTION_I_HAD_A_SIMILAR_QUESTION_BEFORE										1503
	#define	INTERFACE_QUESTION_YOU_HAD_A_RELATED_QUESTION_BEFORE									1504
	#define	INTERFACE_QUESTION_I_HAD_A_RELATED_QUESTION_BEFORE										1505
	#define	INTERFACE_QUESTION_I_DONT_KNOW_ANYTHING_ABOUT_WORD_START								1506
	#define	INTERFACE_QUESTION_I_DONT_KNOW_ANYTHING_ABOUT_WORD_END									1507
	#define	INTERFACE_QUESTION_IS_ALREADY_ANSWERED													1508
	#define	INTERFACE_QUESTION_I_DONT_KNOW_THE_ANSWER_TO_THIS_QUESTION								1509

	// Sentence (notifications)
	#define	INTERFACE_SENTENCE_NOTIFICATION_I_EXPECTED_PROPER_NAME_TO_BE							1600
	#define	INTERFACE_SENTENCE_NOTIFICATION_I_EXPECTED_SINGULAR_NOUN_TO_BE							1601
	#define	INTERFACE_SENTENCE_NOTIFICATION_I_EXPECTED_FEMININE										1602
	#define	INTERFACE_SENTENCE_NOTIFICATION_I_EXPECTED_MASCULINE									1603
	#define	INTERFACE_SENTENCE_NOTIFICATION_I_KNOW													1604
	#define	INTERFACE_SENTENCE_NOTIFICATION_I_NOTICED_SEMANTIC_AMBIGUITY_START						1605
	#define	INTERFACE_SENTENCE_NOTIFICATION_STATIC_SEMANTIC_AMBIGUITY_END							1606
	#define	INTERFACE_SENTENCE_NOTIFICATION_DYNAMIC_SEMANTIC_AMBIGUITY_END							1607
	#define	INTERFACE_SENTENCE_NOTIFICATION_AMBIGUOUS_DUE_TO_SPECIFICATION_START					1608
	#define	INTERFACE_SENTENCE_NOTIFICATION_AMBIGUOUS_DUE_TO_SPECIFICATION_WORD						1609
	#define	INTERFACE_SENTENCE_NOTIFICATION_AMBIGUOUS_DUE_TO_SPECIFICATION_END						1610
	#define	INTERFACE_SENTENCE_NOTIFICATION_AMBIGUOUS_QUESTION_MISSING_RELATION						1611
	#define	INTERFACE_SENTENCE_NOTIFICATION_MISSING_RELATION_I_ASSUME_YOU_MEAN						1612
	#define	INTERFACE_SENTENCE_NOTIFICATION_USED_DIFFERENT_ADJECTIVE_WITH_NOUN_START				1613
	#define	INTERFACE_SENTENCE_NOTIFICATION_USED_DIFFERENT_DEFINITE_ARTICLE_WITH_NOUN_START			1614
	#define	INTERFACE_SENTENCE_NOTIFICATION_USED_DIFFERENT_INDEFINITE_ARTICLE_WITH_NOUN_START		1615
	#define	INTERFACE_SENTENCE_NOTIFICATION_USED_DIFFERENT_ADJECTIVE_OR_ARTICLE_WITH_NOUN_END		1616
	#define	INTERFACE_SENTENCE_NOTIFICATION_YOU_ENTERED_UNKNOWN_PLURAL_OF_SINGULAR_NOUN_START		1617
	#define	INTERFACE_SENTENCE_NOTIFICATION_YOU_ENTERED_UNKNOWN_PLURAL_OF_SINGULAR_NOUN_END			1618

	// Sentence (warnings)
	#define	INTERFACE_SENTENCE_WARNING_NOT_CONFORM_GRAMMAR											1620
	#define	INTERFACE_SENTENCE_WARNING_DONT_UNDERSTAND_FROM_WORD_POSITION_START						1621
	#define	INTERFACE_SENTENCE_WARNING_DONT_UNDERSTAND_FROM_WORD_START								1622
	#define	INTERFACE_SENTENCE_WARNING_DONT_UNDERSTAND_FROM_WORD_END								1623
	#define	INTERFACE_SENTENCE_WARNING_WORD_CAN_ONLY_BE_USED_IN_CONDITION_OF_SELECTION_START		1624
	#define	INTERFACE_SENTENCE_WARNING_WORD_CAN_ONLY_BE_USED_IN_CONDITION_OF_SELECTION_POSITION		1625
	#define	INTERFACE_SENTENCE_WARNING_WORD_CAN_ONLY_BE_USED_IN_CONDITION_OF_SELECTION_END			1626
	#define	INTERFACE_SENTENCE_WARNING_NOT_ABLE_TO_LINK_YES_NO_TO_QUESTION							1627
	#define	INTERFACE_SENTENCE_WARNING_AMBIGUOUS_SENTENCE_MISSING_RELATION							1628
	#define	INTERFACE_SENTENCE_WARNING_AMBIGUOUS_SENTENCE_MULTIPLE_SPECIFICATIONS_RELATIONS			1629

	// Sentence (errors)
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_STORE_OR_RETRIEVE							1630
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_THIS_SENTENCE								1631
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_THIS_SENTENCE_DUE_TO_WORDS					1632
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_SENTENCE_START								1633
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_SENTENCE										1634
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_SENTENCE_DUE_TO_WORDS						1635
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_I_RETRIEVED_FROM_MY_SYSTEM_START				1636
	#define	INTERFACE_SENTENCE_ERROR_GRAMMAR_INTEGRITY_I_RETRIEVED_FROM_MY_SYSTEM_END				1637

#endif

/*************************************************************************
 *	"He will bless those who fear the Lord,
 *	both great and lowly." (Psalm 115:13)
 *************************************************************************/
